version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm install

  pre_build:
    commands:
      - echo "Running pre-build tasks..."
      - npm run lint || true  # lint 실패해도 계속 진행

  build:
    commands:
      - echo "Building Vite React application..."
      - npm run build
      - echo "Build completed successfully"

  post_build:
    commands:
      - echo "Preparing artifacts for deployment..."
      - ls -la dist/

artifacts:
  files:
    - '**/*'
  base-directory: dist
  name: frontend-build-$(date +%Y%m%d-%H%M%S)

cache:
  paths:
    - 'node_modules/**/*'